### PR TITLE
fix(k8s): reduce requests/limits

### PR DESCRIPTION
**Pull request by revolunet**
Based on data in grafana/prod :

Capture d’écran 2020-09-28 à 15 09 45

Capture d’écran 2020-09-28 à 15 09 50

### CODE REVIEW

**Comment by douglasduteil** [comment]
image

**Comment by revolunet** [comment]
cluster full ?

**Comment by douglasduteil** [comment]
Image not pulled ?

**Comment by revolunet** [comment]
looks like fixed

**Comment by douglasduteil** [comment]
@revolunet Did you test the impact on the cdtn pipeline ?
Note 
- that changing the `requests` will change the `hpa` behavior
- that changing the `limits` will have an overall impact on the request handled per sec 

Are the bench similar to `cpu=1000, memory=3Gi offers 17req/s`

**Comment by douglasduteil** [comment]
I use a `Register data image` on the cdtn pipeline to bench the impact on the preprod of serving-ml

**Comment by douglasduteil** [comment]
Currently it scales because it hits 80% of the memory at any request (I think)
image

**Comment by revolunet** [comment]
based on grafana data, hpa is unecessary imho

**Comment by douglasduteil** [comment]
K...
Half a CPU in production
Half a CPU in preprod of x pipeline is enough ?

**Comment by revolunet** [comment]
not sure about HPA, this is the wildest peak on preprod : 

Capture d’écran 2020-09-29 à 13 49 59

**Review by douglasduteil — APPROVED** [review]

**Comment by douglasduteil** [comment]
K let's try this

**Pull request merged**
